const titles={dashboard:'Dashboard Content',promo:'Kelola Promo',harga:'Kelola Daftar Harga',galeri:'Kelola Galeri',layanan:'Kelola Layanan'};
const quick=[['promo','badge-percent','Promo','Buat dan jadwalkan campaign'],['harga','receipt-text','Daftar Harga','Perbarui harga treatment'],['galeri','images','Galeri','Upload hasil pengerjaan'],['layanan','sparkles','Layanan','Atur layanan yang tersedia']];
const prices=[['Deep Cleaning','Cleaning','Rp 45.000'],['Unyellowing','Treatment','Rp 75.000'],['Repaint','Restorasi','Rp 150.000']];
const services=[['Deep Cleaning','assets/layanan-deep-cleaning.jpg'],['Unyellowing','assets/layanan-unyellowing.jpg'],['Repaint','assets/layanan-repaint.jpg']];
const gallery=Array.from({length:6},(_,i)=>[`Hasil perawatan ${i+1}`,`assets/gallery-${i+1}.jpg`]);
const nav=document.querySelectorAll('[data-tab]'), views=document.querySelectorAll('.tab-view');
function switchTab(id){if(!titles[id])id='dashboard';views.forEach(v=>v.classList.toggle('active',v.id===id));nav.forEach(n=>n.classList.toggle('active',n.dataset.tab===id));pageTitle.textContent=titles[id];sidebar.classList.remove('open');window.scrollTo(0,0)}
nav.forEach(n=>n.onclick=()=>{switchTab(n.dataset.tab);history.replaceState(null,'',`#${n.dataset.tab}`)});
const initialTab=window.location.hash.slice(1);if(initialTab)switchTab(initialTab);window.addEventListener('hashchange',()=>switchTab(window.location.hash.slice(1)));
quickLinks.innerHTML=quick.map(([id,icon,title,desc])=>`<button data-go="${id}" class="text-left border border-slate-200 rounded-xl p-4 hover:border-blue-300 hover:bg-blue-50/40 transition"><i data-lucide="${icon}" class="w-5 text-blue-600"></i><b class="block mt-3 text-sm">${title}</b><span class="text-xs text-slate-400">${desc}</span></button>`).join('');
document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>switchTab(x.dataset.go));
document.querySelectorAll('.section-head').forEach((x)=>{const id=x.closest('section').id;x.innerHTML=`<div class="mb-7"><p class="text-sm text-blue-600 font-semibold">CONTENT MANAGER</p><h2 class="text-3xl font-extrabold tracking-tight mt-1">${titles[id]}</h2><p class="text-slate-500 text-sm mt-2">Perubahan di sini akan mengatur konten website publik setelah diterbitkan.</p></div>`});
priceRows.innerHTML=prices.map(([name,cat,price])=>`<tr class="border-t"><td class="p-4 font-semibold">${name}</td><td class="p-4 text-slate-500">${cat}</td><td class="p-4 font-semibold">${price}</td><td class="p-4"><span class="text-xs bg-emerald-50 text-emerald-700 px-2 py-1 rounded-full">Aktif</span></td><td class="p-4 text-right"><button class="btn btn-soft edit-btn" data-type="harga">Edit</button></td></tr>`).join('');
galleryGrid.innerHTML=gallery.map(([name,img])=>`<article class="panel overflow-hidden"><img src="${img}" alt="${name}" class="w-full h-52 object-cover"><div class="p-4 flex items-center justify-between gap-3"><div><b class="text-sm">${name}</b><p class="text-xs text-slate-400 mt-1">Tampil di landing page</p></div><button class="btn btn-soft edit-btn" data-type="galeri"><i data-lucide="pencil" class="w-4"></i></button></div></article>`).join('');
serviceGrid.innerHTML=services.map(([name,img])=>`<article class="panel overflow-hidden flex flex-col"><img src="${img}" alt="${name}" class="w-full h-48 object-cover"><div class="p-5 flex flex-col flex-1"><div class="flex justify-between gap-3"><h3 class="font-bold">${name}</h3><span class="text-xs text-emerald-700">Aktif</span></div><p class="text-xs text-slate-500 leading-5 mt-3">Rekomendasi treatment setelah pemeriksaan kondisi.</p><button class="btn btn-soft edit-btn mt-5" data-type="layanan"><i data-lucide="pencil" class="w-4"></i>Edit Layanan</button></div></article>`).join('');
function openEditor(type){modalTitle.textContent=type==='galeri'?'Upload Foto':`Edit ${titles[type]||'Konten'}`;modal.classList.remove('hidden');modal.classList.add('flex');document.body.style.overflow='hidden';contentTitle.focus()}
function closeEditor(){modal.classList.add('hidden');modal.classList.remove('flex');document.body.style.overflow=''}
document.addEventListener('click',e=>{const b=e.target.closest('.edit-btn');if(b)openEditor(b.dataset.type)});
closeModal.onclick=cancelModal.onclick=closeEditor;modal.onclick=e=>{if(e.target===modal)closeEditor()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeEditor()});
editForm.onsubmit=e=>{e.preventDefault();closeEditor();toast.classList.remove('translate-y-24','opacity-0');setTimeout(()=>toast.classList.add('translate-y-24','opacity-0'),2200)};
openMenu.onclick=()=>sidebar.classList.add('open');closeMenu.onclick=()=>sidebar.classList.remove('open');
if(window.lucide)lucide.createIcons(); else window.addEventListener('load',()=>lucide?.createIcons());
