const core=window.KhufCashierCore;
const rupiah=value=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(value||0);
const pdfRupiah=value=>`Rp ${new Intl.NumberFormat('id-ID',{maximumFractionDigits:0}).format(value||0)}`;
let cart=[];let activeFilter='Semua';let latestOrder=null;let receiptLogoData='';

function renderIcons(){if(window.lucide?.createIcons)window.lucide.createIcons()}
function renderIconsWhenReady(attempt=0){if(window.lucide?.createIcons)return renderIcons();if(attempt<20)setTimeout(()=>renderIconsWhenReady(attempt+1),100)}
function loadReceiptLogo(){const image=new Image();image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;canvas.getContext('2d').drawImage(image,0,0);receiptLogoData=canvas.toDataURL('image/png')};image.src='assets/khuf-logo.png'}
function customerComplete(){return Boolean(customerName.value.trim()&&customerPhone.value.trim())}
function updateCustomerReady(){continueToCatalogButton.disabled=!customerComplete()}

function showCustomerStep(){customerStep.classList.remove('hidden');catalogStep.classList.add('hidden');mobileCartButton.classList.add('hidden');mobileCartButton.classList.remove('flex');pageHeading.textContent='Data Pelanggan';progressCustomer.className='progress-dot active';progressService.className='progress-dot';progressDetail.className='progress-dot';progressPayment.className='progress-dot';window.scrollTo({top:0,behavior:'smooth'})}
function showCatalogStep(){if(!customerComplete())return;customerStep.classList.add('hidden');catalogStep.classList.remove('hidden');mobileCartButton.classList.remove('hidden');mobileCartButton.classList.add('flex');pageHeading.textContent='Pilih Treatment';selectedCustomerSummary.innerHTML=`Order untuk <b class="text-slate-900">${customerName.value}</b> · ${customerPhone.value}`;progressCustomer.className='progress-dot done';progressCustomer.innerHTML='<i data-lucide="check" class="w-3.5"></i>';progressService.className='progress-dot active';window.scrollTo({top:0,behavior:'smooth'});renderIcons()}

function renderCatalog(){const term=serviceSearch.value.trim().toLowerCase();const products=core.catalog.filter(item=>(activeFilter==='Semua'||item.category===activeFilter)&&`${item.category} ${item.service} ${item.description}`.toLowerCase().includes(term));serviceCatalog.innerHTML=products.map(item=>`<button type="button" class="catalog-card" data-catalog-id="${item.id}" aria-label="Tambah ${item.service} ${item.category} ke keranjang"><div class="flex justify-between items-start"><span class="catalog-icon w-11 h-11 rounded-xl bg-${item.color}-50 text-${item.color}-700 grid place-items-center"><i data-lucide="${item.icon}" class="w-5"></i></span><span class="category-badge text-[11px] font-bold text-slate-600 bg-slate-100 px-2.5 py-1 rounded-full">${item.category}</span></div><h3 class="catalog-title font-extrabold mt-5">${item.service}</h3><p class="catalog-description text-xs text-slate-500 leading-5 mt-2 flex-1">${item.description}</p><div class="catalog-footer flex items-center justify-between gap-2 pt-4 mt-4 border-t"><b class="catalog-price text-sm">${rupiah(item.price)}</b><span class="catalog-add w-11 h-11 rounded-xl bg-blue-600 text-white grid place-items-center"><i data-lucide="plus" class="w-4"></i></span></div></button>`).join('')||'<div class="col-span-full panel p-8 text-center text-sm text-slate-400">Treatment tidak ditemukan.</div>';renderIcons()}

function collectItems(){return cart.map(item=>({...item}))}
function calculate(){const total=core.calculateOrderTotal(cart);if(paymentStatus.value==='paid')amountPaid.value=total;if(paymentStatus.value==='unpaid')amountPaid.value=0;return{total,payment:core.calculatePayment(total,amountPaid.value)}}
function renderCart(){cartCount.textContent=cart.reduce((sum,item)=>sum+item.quantity,0);mobileCartCount.textContent=`${cartCount.textContent} barang`;cartEmpty.classList.toggle('hidden',cart.length>0);cartItems.innerHTML=cart.map(item=>`<article class="cart-row" data-cart-id="${item.catalogId}"><div class="flex justify-between gap-3"><div><p class="text-[10px] text-blue-600 font-bold">${item.category.toUpperCase()}</p><h3 class="font-bold text-sm mt-1">${item.service}</h3><p class="text-xs text-slate-400 mt-1">${rupiah(item.price)} / barang</p></div><b class="text-sm">${rupiah(core.calculateLineTotal(item.price,item.quantity))}</b></div><div class="flex items-center justify-between mt-3 pt-3 border-t"><button type="button" class="text-xs text-rose-600 font-semibold cart-remove">Hapus</button><div class="flex items-center gap-2"><button type="button" class="qty-btn cart-decrease" aria-label="Kurangi ${item.service}"><i data-lucide="minus" class="w-3"></i></button><b class="text-sm min-w-5 text-center">${item.quantity}</b><button type="button" class="qty-btn cart-increase" aria-label="Tambah ${item.service}"><i data-lucide="plus" class="w-3"></i></button></div></div></article>`).join('');const{total,payment}=calculate();orderTotal.textContent=mobileCartTotal.textContent=checkoutTotal.textContent=rupiah(total);summaryPaid.textContent=rupiah(payment.paid);amountDue.textContent=checkoutDue.textContent=rupiah(payment.due);checkoutButton.disabled=!cart.length;renderCheckoutItems();validateReady();renderIcons()}

function renderCheckoutItems(){checkoutItems.innerHTML=cart.map((item,index)=>`<article class="cart-row" data-checkout-id="${item.catalogId}"><div class="flex items-center justify-between gap-3 mb-3"><div><p class="text-[10px] text-blue-600 font-bold">ITEM ${index+1} · ${item.category.toUpperCase()}</p><h4 class="font-bold text-sm mt-1">${item.service} × ${item.quantity}</h4></div><b class="text-sm">${rupiah(core.calculateLineTotal(item.price,item.quantity))}</b></div><div class="grid md:grid-cols-[1.2fr_.8fr] gap-3"><label class="label">Nama / merek<input class="field mt-1.5 detail-name" required value="${item.name||''}" placeholder="Contoh: Nike Air Force 1"></label><label class="label">Kondisi singkat<input class="field mt-1.5 detail-notes" value="${item.notes||''}" placeholder="Noda berat, lem terbuka, dll"></label></div></article>`).join('');paymentItems.innerHTML=cart.map(item=>`<div class="flex justify-between gap-3 text-sm"><span>${item.quantity}× ${item.category} — ${item.service}</span><b>${rupiah(core.calculateLineTotal(item.price,item.quantity))}</b></div>`).join('')}
function persistCheckoutDetails(card){const item=cart.find(row=>row.catalogId===card.dataset.checkoutId);if(!item)return;item.name=card.querySelector('.detail-name').value.trim();item.notes=card.querySelector('.detail-notes').value.trim()}
function validateReady(){const{payment}=calculate();const itemsComplete=cart.length>0&&cart.every(item=>item.name);const paymentComplete=paymentStatus.value==='unpaid'||Boolean(paymentMethod.value&&(paymentStatus.value!=='partial'||payment.paid>0));createOrderButton.disabled=!(customerComplete()&&itemsComplete&&paymentComplete)}

customerSearch.addEventListener('input',()=>{const matches=core.findCustomers(customerSearch.value);customerResults.innerHTML=matches.map(customer=>`<button type="button" class="w-full text-left p-3 border-b last:border-b-0 hover:bg-blue-50" data-customer-id="${customer.id}"><b class="text-sm">${customer.name}</b><p class="text-xs text-slate-400 mt-1">${customer.phone} · ${customer.address}</p></button>`).join('');customerResults.classList.toggle('hidden',!matches.length)});
customerResults.addEventListener('click',event=>{const button=event.target.closest('[data-customer-id]');if(!button)return;const customer=core.customers.find(item=>item.id===Number(button.dataset.customerId));customerName.value=customer.name;customerPhone.value=customer.phone;customerAddress.value=customer.address;customerSearch.value=customer.name;customerResults.classList.add('hidden');existingCustomerNote.classList.remove('hidden');updateCustomerReady()});
[customerName,customerPhone,customerAddress].forEach(input=>input.addEventListener('input',updateCustomerReady));continueToCatalogButton.addEventListener('click',showCatalogStep);editCustomerButton.addEventListener('click',showCustomerStep);
serviceCatalog.addEventListener('click',event=>{const card=event.target.closest('[data-catalog-id]');if(!card)return;cart=core.addCatalogItem(cart,card.dataset.catalogId);renderCart()});serviceSearch.addEventListener('input',renderCatalog);catalogFilters.addEventListener('click',event=>{const button=event.target.closest('[data-filter]');if(!button)return;activeFilter=button.dataset.filter;catalogFilters.querySelectorAll('[data-filter]').forEach(item=>item.className=`btn ${item===button?'btn-primary':'btn-soft'} whitespace-nowrap min-h-11`);renderCatalog()});cartItems.addEventListener('click',event=>{const row=event.target.closest('[data-cart-id]');if(!row)return;const id=row.dataset.cartId;if(event.target.closest('.cart-increase'))cart=core.updateCartQuantity(cart,id,1);if(event.target.closest('.cart-decrease'))cart=core.updateCartQuantity(cart,id,-1);if(event.target.closest('.cart-remove'))cart=cart.filter(item=>item.catalogId!==id);renderCart()});
function openCart(){cartPanel.classList.add('open');cartBackdrop.classList.add('open');document.body.style.overflow='hidden'}function closeCart(){cartPanel.classList.remove('open');cartBackdrop.classList.remove('open');document.body.style.overflow=''}mobileCartButton.addEventListener('click',openCart);closeCartButton.addEventListener('click',closeCart);cartBackdrop.addEventListener('click',closeCart);
function openCheckout(){if(!cart.length)return;closeCart();checkoutModal.classList.remove('hidden');checkoutModal.classList.add('flex');document.body.style.overflow='hidden';progressService.className='progress-dot done';progressService.innerHTML='<i data-lucide="check" class="w-3.5"></i>';progressDetail.className='progress-dot active';renderIcons()}function closeCheckout(){checkoutModal.classList.add('hidden');checkoutModal.classList.remove('flex');document.body.style.overflow='';progressDetail.className='progress-dot';progressService.className='progress-dot active'}checkoutButton.addEventListener('click',openCheckout);closeCheckoutButton.addEventListener('click',closeCheckout);cancelCheckoutButton.addEventListener('click',closeCheckout);
checkoutItems.addEventListener('input',event=>{const card=event.target.closest('[data-checkout-id]');if(!card)return;persistCheckoutDetails(card);validateReady()});orderPhoto.addEventListener('change',()=>{orderPhotoName.innerHTML=orderPhoto.files[0]?`<span class="photo-name"><i data-lucide="image" class="w-3"></i>${orderPhoto.files[0].name}</span>`:'';renderIcons()});paymentStatus.addEventListener('change',()=>{amountPaid.disabled=paymentStatus.value==='unpaid'||paymentStatus.value==='paid';renderCart()});paymentMethod.addEventListener('change',validateReady);amountPaid.addEventListener('input',renderCart);

cashierForm.addEventListener('submit',event=>{event.preventDefault();if(createOrderButton.disabled)return;const{total,payment}=calculate();latestOrder={number:'KHUF-260731-006',date:'31 Juli 2026, 14:30',branch:'Pejaten Barat',customer:{name:customerName.value.trim(),phone:customerPhone.value.trim(),address:customerAddress.value.trim()},items:collectItems(),orderPhotoCount:orderPhoto.files.length,total,payment,method:paymentMethod.value||'Belum ditentukan'};successOrderNumber.textContent=latestOrder.number;successTotal.textContent=rupiah(total);successDue.textContent=rupiah(payment.due);successPaymentBadge.textContent=payment.status;successPaymentBadge.className=`inline-flex rounded-full px-3 py-1 text-xs font-bold mt-4 ${payment.status==='LUNAS'?'bg-emerald-50 text-emerald-700':payment.status==='DP'?'bg-blue-50 text-blue-700':'bg-amber-50 text-amber-700'}`;closeCheckout();progressDetail.className='progress-dot done';progressPayment.className='progress-dot done';orderSuccess.classList.remove('hidden');orderSuccess.classList.add('flex');document.body.style.overflow='hidden';renderIcons()});
function generateReceiptPdf(order){if(!window.jspdf?.jsPDF)throw new Error('PDF library belum siap. Coba ulangi beberapa detik lagi.');const{jsPDF}=window.jspdf;const height=Math.max(190,125+order.items.length*20);const doc=new jsPDF({unit:'mm',format:[80,height]});if(receiptLogoData)doc.addImage(receiptLogoData,'PNG',24,7,32,18,undefined,'FAST');else{doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('KHUF',40,15,{align:'center'})}doc.setTextColor(15,23,42);doc.setFontSize(8);doc.setFont('helvetica','normal');doc.text(order.branch,40,35,{align:'center'});doc.text('+62 899-1971-197',40,40,{align:'center'});doc.setDrawColor(203,213,225);doc.line(5,45,75,45);let y=51;doc.setFont('helvetica','bold');doc.text(order.number,5,y);doc.setFont('helvetica','normal');doc.text(order.date,75,y,{align:'right'});y+=7;doc.text(`Pelanggan: ${order.customer.name}`,5,y);y+=5;doc.text(`WhatsApp: ${order.customer.phone}`,5,y);y+=5;if(order.customer.address){const lines=doc.splitTextToSize(`Alamat: ${order.customer.address}`,70);doc.text(lines,5,y);y+=lines.length*4+2}doc.line(5,y,75,y);y+=6;order.items.forEach(item=>{doc.setFont('helvetica','bold');doc.text(`${item.quantity}x ${item.name}`,5,y);doc.setFont('helvetica','normal');doc.text(pdfRupiah(core.calculateLineTotal(item.price,item.quantity)),75,y,{align:'right'});y+=4.5;doc.setFontSize(7);doc.text(`${item.category} - ${item.service} @ ${pdfRupiah(item.price)}`,5,y);doc.setFontSize(8);y+=7});doc.line(5,y,75,y);y+=7;doc.setFont('helvetica','bold');doc.text('TOTAL',5,y);doc.text(pdfRupiah(order.total),75,y,{align:'right'});y+=6;doc.setFont('helvetica','normal');doc.text(`Dibayar (${order.method})`,5,y);doc.text(pdfRupiah(order.payment.paid),75,y,{align:'right'});y+=6;doc.text('Sisa tagihan',5,y);doc.text(pdfRupiah(order.payment.due),75,y,{align:'right'});y+=9;doc.setFont('helvetica','bold');doc.text(order.payment.status,40,y,{align:'center'});return doc}
downloadReceiptButton.addEventListener('click',()=>{try{generateReceiptPdf(latestOrder).save(`Struk-${latestOrder.number}.pdf`)}catch(error){alert(error.message)}});shareWhatsappButton.addEventListener('click',()=>{if(!latestOrder)return;const message=`Halo ${latestOrder.customer.name}, order ${latestOrder.number} sudah dibuat. Total ${rupiah(latestOrder.total)}, status ${latestOrder.payment.status}, sisa ${rupiah(latestOrder.payment.due)}.`;window.open(`https://wa.me/${latestOrder.customer.phone.replace(/\D/g,'').replace(/^0/,'62')}?text=${encodeURIComponent(message)}`,'_blank','noopener')});document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeCart();closeCheckout()}});
renderCatalog();renderCart();updateCustomerReady();loadReceiptLogo();renderIconsWhenReady();setTimeout(renderIcons,500);window.addEventListener('load',()=>setTimeout(renderIcons,100));window.KhufCashier={getCart:()=>cart.map(item=>({...item})),collectItems,renderCart,showCatalogStep,generateReceiptPdf,getLatestOrder:()=>latestOrder};
