server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
    add_header Cache-Control "no-cache, must-revalidate";
  }

  location ~* \.js$ {
    expires -1;
    add_header Cache-Control "no-store, no-cache, must-revalidate";
  }

  location ~* \.(?:css|jpg|jpeg|png|webp|svg)$ {
    expires 7d;
    add_header Cache-Control "public, max-age=604800";
  }
}
